name: location_favorites
description: A Flutter app to manage favorite locations with SQLite database.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  uuid: ^4.5.1
  google_maps_flutter: ^2.13.1
  path: ^1.9.1
  geolocator: ^14.0.2

  # google_places_flutter: ^2.1.1
  # geocoding: ^4.0.0
  # geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
